name: Node Test Learning
on:
    push:
        branches:
            - main
jobs:
    Execute-Node-File:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Node Js
              uses: actions/setup-node@v3
              with:
                node-version: latest
            
            - name : Java JDK
              uses : actions/setup-python@v4
              with:
                  python-version: latest

            - name: Node Version Checker
              run: node -v
              
            - name: Python Version Checker
              run: python --version

            - name: JavaScript File Run
              run: node index.js
